### ISSUE TITLE
Youtube Stream EOFs in the middle of stream

### ISSUE THREAD

**Issue by RinDoesJava** [jonas747/dca#8]
So this is a weird issue that I kind of understand. From what I know, Google times out because it expects everything to be buffered, when in reality FFMPEG buffers slowly as it goes on. I don't know how easy this is to fix, but it's rather annoying to get an EOF in the middle of a song that's longer than a minute.

**Comment by jonas747** [comment]
Add a bufio.Reader or something, that's outside the scope of what this package is responsible for. (the caller is responsible for the input, if dca consumes it too slow, then just put a buffer in)
